[build]
  publish = "/"
  command = "echo 'No build command needed'"  # Use this if you're not running a build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

